# パッケージのREADMEに記載のデフォルトはこちらの厳しいルール
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    directives_ordering: false
    flutter_style_todos: false
