import 'package:flutter/widgets.dart';
/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///


class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData chat =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heartEmpty =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData home =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData personOutline =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData keyboardArrowDown =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData keyboardArrowLeft =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData keyboardArrowUp =
      IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bell =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData chatAlt =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edit =
      IconData(0xe809, fontFamily: _kFontFam);
  static const IconData beat =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData arrowsRight =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData logosSpotifyIcon =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData playArrow =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData playCircleOutline =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData playCircleFilled =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData music =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData path4 =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData checkmarkCicle =
      IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData menu =
      IconData(0xf0c9, fontFamily: _kFontFam);
}
