name: Flutter_Analyzer_Formatter

on:
  pull_request:
    branches: [main]

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format lib/ --set-exit-if-changed